project:
  type: website

website:
  title: "first_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
        text: Sources
  
  sources:
    - id: interactive
      title: "Interactive Pages"
      style: "floating"
      background: "#ffffff"
      collapse-level: 3
      contents: 
        - plane-passengers.qmd
        - map-london.qmd
        - plotly.qmd


    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
